# Generated by Django 5.2.8 on 2025-11-06 23:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O telefone deve estar no formato: '+999999999'. Até 15 dígitos permitidos.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Celular')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('categoria', models.CharField(choices=[('familia', 'Família'), ('amigo', 'Amigo'), ('trabalho', 'Trabalho'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria')),
                ('empresa', models.CharField(blank=True, max_length=200, null=True, verbose_name='Empresa')),
                ('cargo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Cargo')),
                ('aniversario', models.DateField(blank=True, null=True, verbose_name='Aniversário')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_contatos/', verbose_name='Foto')),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['nome'],
            },
        ),
    ]
