# Generated by Django 5.2.8 on 2025-11-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='foto',
        ),
    ]
